 name: flutter_app
 description: A new Flutter application.

 # The following defines the version and build number for your application.
 # A version number is three numbers separated by dots, like 1.2.43
 # followed by an optional build number separated by a +.
 # Both the version and the builder number may be overridden in flutter
 # build by specifying --build-name and --build-number, respectively.
 # In Android, build-name is used as versionName while build-number used as versionCode.
 # Read more about Android versioning at https://developer.android.com/studio/publish/versioning
 # In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
 # Read more about iOS versioning at
 # https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
 version: 1.0.0+1

 environment:
   sdk: ">=2.2.2 <3.0.0"

 dependencies:
   flutter:
     sdk: flutter

   # The following adds the Cupertino Icons font to your application.
   # Use with the CupertinoIcons class for iOS style icons.
   cupertino_icons: ^0.1.2
   carousel_pro: ^1.0.0
   font_awesome_flutter: 8.8.1
   url_launcher: ^5.5.1
   gradient_text: ^1.0.2
   provider: ^4.3.2+2
   scoped_model: ^1.0.1
   firebase_auth: ^0.18.0+1
   modal_progress_hud: ^0.1.3
   firebase_core: ^0.5.0
   cloud_firestore: ^0.14.0+2
   google_maps_webservice: ^0.0.18
   flutter_google_places: ^0.2.6
   shared_preferences: ^0.5.10
   stripe_payment: ^1.0.7
   flutter_credit_card: ^0.1.3
   progress_dialog: ^1.2.4
   http: ^0.12.2
   mailer: ^3.2.1
   smtp: ^1.0.0+1
   google_fonts: ^1.1.1


 dev_dependencies:
   flutter_test:
     sdk: flutter
   flutter_launcher_icons: ^0.8.0


 flutter_icons:
   android: true
   ios: true
   image_path: assets/images/unnamed.png


 # For information on the generic Dart part of this file, see the
 # following page: https://dart.dev/tools/pub/pubspec

 # The following section is specific to Flutter.
 flutter:

   # The following line ensures that the Material Icons font is
   # included with your application, so that you can use the icons in
   # the material Icons class.
   uses-material-design: true

   # To add assets to your application, add an assets section, like this:
   # assets:
   #  - images/a_dot_burr.jpeg
   #  - images/a_dot_ham.jpeg
   assets:

     - assets/images/menus/ic_delete.png
     - assets/images/menus/ic_credit_card.png
     - assets/images/Lyoom-5.jpg
     - assets/images/Lyoom-1.jpg
     - assets/images/topmenu/casse-dalle.jpg
     - assets/images/topmenu/dessert.jpg
     - assets/images/topmenu/extras.jpg
     - assets/images/topmenu/formule-midi.jpg
     - assets/images/topmenu/mezzés.jpg
     - assets/images/topmenu/softs.jpg
     - assets/images/bestfood/best-food1.jpg
     - assets/images/bestfood/best-food2.jpg
     - assets/images/bestfood/best-food3.jpg
     - assets/images/bestfood/best-food4.jpg
     - assets/images/bestfood/best-food5.jpg
     - assets/images/bestfood/best-food6.jpg
     - assets/images/bestfood/best-food7.jpg
     - assets/images/bestfood/best-food8.jpg
     - assets/images/popular_foods/brick.jpg
     - assets/images/popular_foods/citronade.jpg
     - assets/images/popular_foods/keskroutekefteji.jpg
     - assets/images/popular_foods/melawi.jpg
     - assets/images/popular_foods/mezzés2.jpg
     - assets/images/lyoomcantine.png
     - assets/images/menus/lyoomcantine.png
     - assets/images/lyoom images/
     - assets/images/lyoom.png
     - assets/images/unnamed.png
     - assets/images/octa.jpg
   # An image asset can refer to one or more resolution-specific "variants", see
   # https://flutter.dev/assets-and-images/#resolution-aware.

   # For details regarding adding assets from package dependencies, see
   # https://flutter.dev/assets-and-images/#from-packages

   # To add custom fonts to your application, add a fonts section here,
   # in this "flutter" section. Each entry in this list should have a
   # "family" key with the font family name, and a "fonts" key with a
   # list giving the asset and other descriptors for the font. For
   # example:
   # fonts:
   #   - family: Schyler
   #     fonts:
   #       - asset: fonts/Schyler-Regular.ttf
   #       - asset: fonts/Schyler-Italic.ttf
   #         style: italic
   #   - family: Trajan Pro
   #     fonts:
   #       - asset: fonts/TrajanPro.ttf
   #       - asset: fonts/TrajanPro_Bold.ttf
   #         weight: 700
   #
   # For details regarding fonts from package dependencies,
   # see https://flutter.dev/custom-fonts/#from-packages
   fonts:
     - family: Roboto
       fonts:
         - asset: assets/fonts/Roboto-Regular.ttf
         - asset: assets/fonts/Roboto-Bold.ttf
         - asset: assets/fonts/Roboto-Light.ttf
